networks:
  cityscope:
    external: true

services:
  notebook-cs:
    container_name: notebooks
    build:
      context: ./jup-note
    restart: always
    ports:
      - "9876:9876"
    volumes:
      - ./jup-note:/app
      - ./assets:/app/assets
      - ./data:/app/data
      - ./scripts:/app/scripts
    networks:
      - cityscope

  indicator-api:
    container_name: indicator_api
    build:
      context: ./indicator-API
    restart: always
    ports:
      - "9875:9875"
    volumes:
      #- ./indicator-API:/app
      - ./data/indicators:/app/data/indicators
    networks:
      - cityscope
#  front-cs:
#    container_name: front_cs
#    build:
#      context: ./front-react
#      #target: development
#    restart: always
#    ports:
#      - "9874:9874"
#    volumes:
#      - ./front-react:/app
#      - /app/node_modules
#    networks:
#      - cityscope
