version: '3'
services:
  mit-cityscope:
    container_name: notebooks
    build: .
    restart: always
    ports:
      - "9876:9876"
    volumes:
      - ./assets:/app/assets
      - ./data:/app/data
      - ./scripts:/app/scripts