networks:
  cityscope:
    external: true

services:
  mit-cityscope:
    container_name: notebooks
    build: .
    restart: always
    ports:
      - "9876:9876"
    volumes:
      # - ./assets:/app/assets
      # - ./data:/app/data
      - ./scripts:/app/scripts
    networks:
      - cityscope
  
  indicator-api:
    container_name: indicator_api
    build:
      context: ./IndicatorAPI
    restart: always
    ports:
      - "9875:9875"  # Puerto para la API de indicadores
    volumes:
      - ./IndicatorAPI:/app
    networks:
      - cityscope

